# -*- coding: utf-8 -*-
"""RegresionLogistica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XV6Brm_esIBjofa5b3g6XYAgBhrk5x5y
"""

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
import numpy as np
import cv2
from google.colab.patches import cv2_imshow
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
import os

def extraer_hist (ruta_imagen):
  image = cv2.imread(ruta_imagen)
  hist = cv2.calcHist([image], [0, 1, 2], None, [8, 8, 8], [0, 256, 0, 256, 0, 256])
  return cv2.normalize(hist, hist).flatten()

def procesar(train_labels, base_path='/content/train'):
  y = []
  X = []
  valid_extensions = ('.jpg', '.jpeg', '.png', '.webp')
  for train_label in train_labels:
    directorio = os.path.join(base_path, train_label)
    if not os.path.exists(directorio): continue
    for filename in os.listdir(directorio):
      if filename.lower().endswith(valid_extensions):
        full_path = os.path.join(directorio, filename)
        histograma = np.hstack(extraer_hist(full_path))
        X.append(histograma)
        y.append(train_label)
  return X, y

etiquetas = ['dbz','snk']

X, y = procesar(etiquetas)

scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

lr = LogisticRegression()
lr.fit(X_train, y_train)

lr.score(X_test,y_test)

lr.score(X_train,y_train)

imagenes_test_ruta = '/content/test'
valid_extensions = ('.jpg', '.jpeg', '.png', '.webp')
for filename in os.listdir(imagenes_test_ruta):
  if filename.lower().endswith(valid_extensions):
    imagen_test_ruta = imagenes_test_ruta + '/' + filename
    imagen_test = np.hstack(extraer_hist(imagen_test_ruta))
    caracteristicas = scaler.transform(imagen_test.reshape(1, -1))
    print(filename, lr.predict(caracteristicas))

!pip install fastapi uvicorn python-multipart nest_asyncio

import zipfile
import shutil

def descomprimir_archivo(archivo_zip, destino):
    with zipfile.ZipFile(archivo_zip, 'r') as zip_ref:
        zip_ref.extractall(destino)

def entrenar_modelo_core(etiquetas, base_path='/content/train'):
    X, y = procesar(etiquetas, base_path=base_path)
    X_np = np.array(X)

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_np)

    model = LogisticRegression(max_iter=1000)
    model.fit(X_scaled, y)

    return model, scaler

def predecir_lote(model, scaler, folder_path):
    resultados = {}
    valid_extensions = ('.jpg', '.jpeg', '.png', '.webp')
    for filename in os.listdir(folder_path):
        if filename.lower().endswith(valid_extensions):
            path = os.path.join(folder_path, filename)
            hist = np.hstack(extraer_hist(path))
            feat = scaler.transform(hist.reshape(1, -1))
            pred = model.predict(feat)
            resultados[filename] = pred[0]
    return resultados

from fastapi import FastAPI, UploadFile, File, Form
from typing import List
import nest_asyncio
import uvicorn
import os

app = FastAPI()

modelo_global = lr
escalador_global = scaler

@app.post("/train")
async def train_endpoint(labels: str = Form(...), files: List[UploadFile] = File(...)):
    global modelo_global, escalador_global

    target_base = "/content/temp_train"
    if os.path.exists(target_base): shutil.rmtree(target_base)
    os.makedirs(target_base)

    label_list = [l.strip() for l in labels.split(",")]

    for i, file in enumerate(files):
        label = label_list[i]
        label_path = os.path.join(target_base, label)
        os.makedirs(label_path, exist_ok=True)

        zip_path = os.path.join(target_base, f"{label}.zip")
        with open(zip_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)

        descomprimir_archivo(zip_path, label_path)
        os.remove(zip_path)

    modelo_global, escalador_global = entrenar_modelo_core(label_list, base_path=target_base)

    return {"status": "Modelo entrenado exitosamente", "etiquetas": label_list}

@app.post("/predict")
async def predict_endpoint(file: UploadFile = File(...)):
    if modelo_global is None:
        return {"error": "El modelo no ha sido entrenado"}

    temp_test = "/content/temp_test"
    if os.path.exists(temp_test): shutil.rmtree(temp_test)
    os.makedirs(temp_test)

    zip_path = "/content/test.zip"
    with open(zip_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)

    descomprimir_archivo(zip_path, temp_test)
    resultados = predecir_lote(modelo_global, escalador_global, temp_test)

    os.remove(zip_path)
    return {"predicciones": resultados}

!pip install pyngrok

from pyngrok import ngrok
import nest_asyncio
import asyncio

NGROK_TOKEN = "3Aus0vohAJn5OBtCzRISJm8uq1S_264ViiFFUX47vgkb1fNYn"
ngrok.set_auth_token(NGROK_TOKEN)

nest_asyncio.apply()

try:
    # Check if a tunnel is already open to avoid errors
    tunnels = ngrok.get_tunnels()
    if not tunnels:
        public_url = ngrok.connect(8000)
    else:
        public_url = tunnels[0].public_url
    print(f"Public URL: {public_url}")
except Exception as e:
    print(f"Ngrok setup error: {e}")

if __name__ == "__main__":
    config = uvicorn.Config(app, host="0.0.0.0", port=8000, loop="asyncio")
    server = uvicorn.Server(config)
    await server.serve()